# Generated by Django 4.1.3 on 2023-12-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrorwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersona',
            name='espejo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
